



version: '3.8'

services:
  db:
    container_name: project-holbies_db
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - project-holbies

  web:
    container_name: project-holbies_web
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - db
    volumes:
      - .:/app
    entrypoint:
      - /bin/sh
      - -c
      - |
        chmod +x /app/wait-for-postgres.sh && /app/wait-for-postgres.sh db uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - project-holbies


networks:
  project-holbies:
    name: project-holbies

volumes:
  postgres_data:
