version: '3.8'

services:
  db:
    container_name: project-holbies_db
    image: postgres:13
    environment:
      POSTGRES_DB: holbies_db
      POSTGRES_USER: holbies_user
      POSTGRES_PASSWORD: holbies_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    container_name: project-holbies_web
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://holbies_user:holbies_password@db/holbies_db
      SECRET_KEY: your-super-secret-key-here-change-in-production
      POSTGRES_USER: holbies_user
      POSTGRES_PASSWORD: holbies_password
      POSTGRES_DB: holbies_db
    depends_on:
      - db
    volumes:
      - .:/app
    entrypoint:
      - /bin/sh
      - -c
      - |
        chmod +x /app/wait-for-postgres.sh && /app/wait-for-postgres.sh db uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data:
